### ISSUE TITLE
Exception: Class initialization must not depend on services. Consider using instance of the service on-demand instead. (IDEA 2024.2.3)

### ISSUE THREAD

**Issue by ristomatti** [a690700752/KJump#73]
After a few jumps the below exception is reported at the same time as #55, so it's possibly a related issue.

Jumping itself works just fine. BTW, this plugin is awesome!

```java
java.lang.Throwable: com.werfad.JumpHandler <clinit> requests com.werfad.UserConfig instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
	at com.werfad.UserConfig.getInstance(UserConfig.java:33)
	at com.werfad.UserConfig.getDataBean(UserConfig.java:38)
	at com.werfad.MarksCanvas.<init>(MarksCanvas.java:103)
	at com.werfad.JumpHandler.<clinit>(JumpHandler.java:32)
	at com.werfad.Actions$BaseAction.actionPerformed(Actions.java:23)
	at com.werfad.Actions$Word0Action.actionPerformed(Actions.java:40)
	at com.maddyhome.idea.vim.helper.IjActionExecutor.executeAction$lambda$0(IjActionExecutor.kt:123)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1164)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:362)
	at com.maddyhome.idea.vim.helper.IjActionExecutor.executeAction(IjActionExecutor.kt:123)
	at com.maddyhome.idea.vim.helper.IjActionExecutor.executeAction(IjActionExecutor.kt:136)
	at com.maddyhome.idea.vim.key.ToActionMappingInfo.execute(MappingInfo.kt:258)
	at com.maddyhome.idea.vim.command.MappingProcessor.processCompleteMappingSequence(MappingProcessor.kt:206)
	at com.maddyhome.idea.vim.command.MappingProcessor.handleCompleteMappingSequence$lambda$8(MappingProcessor.kt:189)
	at com.maddyhome.idea.vim.KeyProcessResult$SynchronousKeyProcessBuilder.build$lambda$1(KeyHandler.kt:482)
	at com.maddyhome.idea.vim.KeyProcessResult$Executable.execute(KeyHandler.kt:443)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:105)
	at com.maddyhome.idea.vim.key.ToKeysMappingInfo.execute(MappingInfo.kt:96)
	at com.maddyhome.idea.vim.command.MappingProcessor.processCompleteMappingSequence(MappingProcessor.kt:206)
	at com.maddyhome.idea.vim.command.MappingProcessor.handleCompleteMappingSequence$lambda$8(MappingProcessor.kt:189)
	at com.maddyhome.idea.vim.KeyProcessResult$SynchronousKeyProcessBuilder.build$lambda$1(KeyHandler.kt:482)
	at com.maddyhome.idea.vim.KeyProcessResult$Executable.execute(KeyHandler.kt:443)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:105)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:86)
	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.kt:80)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:201)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:200)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1368)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1350)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3764)
	at com.intellij.openapi.editor.impl.EditorImpl$6.keyTyped(EditorImpl.java:1182)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2901)
	at java.desktop/java.awt.Component.processEvent(Component.java:6442)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5035)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:886)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1162)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:849)
	at com.intellij.ide.IdeKeyboardFocusManager.access$dispatchEvent$s1569605750(IdeKeyboardFocusManager.kt:28)
	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$dispatch$1.invoke(IdeKeyboardFocusManager.kt:43)
	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$dispatch$1.invoke(IdeKeyboardFocusManager.kt:43)
	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$1.invoke(IdeKeyboardFocusManager.kt:46)
	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$1.invoke(IdeKeyboardFocusManager.kt:46)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.kt:46)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4912)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:623)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$15(IdeEventQueue.kt:582)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:582)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mgusthl** [comment]
Noticed the same errors on my IDEA version 2024.2.4 and also for me the plugin and actions still work normally.

Tried different things by cloning the repo and editing this plugin locally. Got rid of the _"Consider using instance of the service on-demand instead."_ warning by changing the line in JumpHandler.kt line 27
from 
```
    private val mMarksCanvas = MarksCanvas()
```
to
```
    private val mMarksCanvas: MarksCanvas by lazy { MarksCanvas() }
```

Packaged the plugin with gradle command `gradle buildPlugin` and installed the built .zip manually to IDEA from the `build/distributions` directory.

Did not test this much and I'm only using the action KJumpAction.Word0 but figured this might help if you dont like to see the error popup in the IDEA.

Also love this plugin a lot. Thanks for making it :)

**Comment by metepg** [comment]
> After a few jumps the below exception is reported at the same time as #55, so it's possibly a related issue.
> 
> Jumping itself works just fine. BTW, this plugin is awesome!
> 
> ```java
> java.lang.Throwable: com.werfad.JumpHandler <clinit> requests com.werfad.UserConfig instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
> 	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
> 	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
> 	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
> 	at com.werfad.UserConfig.getInstance(UserConfig.java:33)
> 	at com.werfad.UserConfig.getDataBean(UserConfig.java:38)
> 	at com.werfad.MarksCanvas.<init>(MarksCanvas.java:103)
> 	at com.werfad.JumpHandler.<clinit>(JumpHandler.java:32)
> 	at com.werfad.Actions$BaseAction.actionPerformed(Actions.java:23)
> 	at com.werfad.Actions$Word0Action.actionPerformed(Actions.java:40)
> 	at com.maddyhome.idea.vim.helper.IjActionExecutor.executeAction$lambda$0(IjActionExecutor.kt:123)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1164)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:362)
> 	at com.maddyhome.idea.vim.helper.IjActionExecutor.executeAction(IjActionExecutor.kt:123)
> 	at com.maddyhome.idea.vim.helper.IjActionExecutor.executeAction(IjActionExecutor.kt:136)
> 	at com.maddyhome.idea.vim.key.ToActionMappingInfo.execute(MappingInfo.kt:258)
> 	at com.maddyhome.idea.vim.command.MappingProcessor.processCompleteMappingSequence(MappingProcessor.kt:206)
> 	at com.maddyhome.idea.vim.command.MappingProcessor.handleCompleteMappingSequence$lambda$8(MappingProcessor.kt:189)
> 	at com.maddyhome.idea.vim.KeyProcessResult$SynchronousKeyProcessBuilder.build$lambda$1(KeyHandler.kt:482)
> 	at com.maddyhome.idea.vim.KeyProcessResult$Executable.execute(KeyHandler.kt:443)
> 	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:105)
> 	at com.maddyhome.idea.vim.key.ToKeysMappingInfo.execute(MappingInfo.kt:96)
> 	at com.maddyhome.idea.vim.command.MappingProcessor.processCompleteMappingSequence(MappingProcessor.kt:206)
> 	at com.maddyhome.idea.vim.command.MappingProcessor.handleCompleteMappingSequence$lambda$8(MappingProcessor.kt:189)
> 	at com.maddyhome.idea.vim.KeyProcessResult$SynchronousKeyProcessBuilder.build$lambda$1(KeyHandler.kt:482)
> 	at com.maddyhome.idea.vim.KeyProcessResult$Executable.execute(KeyHandler.kt:443)
> 	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:105)
> 	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:86)
> 	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.kt:80)
> 	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:201)
> 	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
> 	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:200)
> 	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1368)
> 	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1350)
> 	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3764)
> 	at com.intellij.openapi.editor.impl.EditorImpl$6.keyTyped(EditorImpl.java:1182)
> 	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
> 	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
> 	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
> 	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6620)
> 	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2901)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6442)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5035)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
> 	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:886)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1162)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:849)
> 	at com.intellij.ide.IdeKeyboardFocusManager.access$dispatchEvent$s1569605750(IdeKeyboardFocusManager.kt:28)
> 	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$dispatch$1.invoke(IdeKeyboardFocusManager.kt:43)
> 	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$dispatch$1.invoke(IdeKeyboardFocusManager.kt:43)
> 	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$1.invoke(IdeKeyboardFocusManager.kt:46)
> 	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$1.invoke(IdeKeyboardFocusManager.kt:46)
> 	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
> 	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
> 	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
> 	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
> 	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
> 	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
> 	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.kt:46)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4912)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
> 	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:623)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$15(IdeEventQueue.kt:582)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:582)
> 	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
> 	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
> 	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
> 	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
> 	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
> 	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
> 	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
> ```

**Comment by metepg** [comment]
Noticed the same error on my IDEA version 2024.2.4 and also for me the plugin and actions still work normally.

Tried different things by cloning the repo and editing this plugin locally. Got rid of the _"Consider using instance of the service on-demand instead."_ warning by changing the line in [JumpHandler.kt line 27](https://github.com/a690700752/KJump/blob/007f880fc398c498a52ed66cb12ac895afd4672f/src/main/kotlin/com/werfad/JumpHandler.kt#L27)

from 
`private val mMarksCanvas = MarksCanvas()`

to
`private val mMarksCanvas: MarksCanvas by lazy { MarksCanvas() }`

Packaged the plugin with gradle command `gradle buildPlugin` and installed the built .zip manually to IDEA from the `build/distributions` directory.

Did not test this much and I'm only using the action KJumpAction.Word0 but figured this might help if you dont like to see the error popup in the IDEA.

Also love this plugin a lot. Thanks for making it :)
